#! /bin/sh

# Autostart Programs

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
picom &
#nitrogen --restore &																		# Restore last desktop wallpaper
feh --bg-scale --randomize ~/Pictures/Wallpaper/* &			# Set random desktop wallpaper
volumeicon &
nm-applet &

# Display Correct Mouse Cursor

xsetroot -cursor_name left_ptr &

# Display Power Settings

xset s off -dpms &																			# Disables screen blanking and power saving

# Workspace Configuration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
