#! /bin/sh

#### AUTOSTART ####
sxhkd &
polybar mainbar-bspwm &
polybar mainbar-bspwm-extra &
xset -b & #For annoying beeping sounds

#### WORKSPACES AND BORDERS #### 

#Monitor allocation and their workspaces

xrandr --output DP2 --auto --mode 1920x1080 --primary 
xrandr --output DP1 --auto --mode 1920x1080 --right-of DP2

bspc wm -O DP2 DP1
bspc monitor DP2 -d 1 2 3 4 5
bspc monitor DP1 -d 6 7 8 9 10

#Border gaps,width, and padding
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          25
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding 	 10

#### OPEN APPLICATIONS ON SPECIFIC WORKSPACES ####

bspc rule -a termite desktop='^1' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Thunderbird desktop='^3' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Pcmanfm desktop='^7' follow=on
bspc rule -a Clementine desktop='^8' follow=on

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
